// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tablespace.proto

package org.yamcs.yarch.rocksdb.protobuf;

public final class Tablespace {
  private Tablespace() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TablespaceRecordOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 tbsIndex = 1;
    /**
     * <code>optional uint32 tbsIndex = 1;</code>
     */
    boolean hasTbsIndex();
    /**
     * <code>optional uint32 tbsIndex = 1;</code>
     */
    int getTbsIndex();

    // optional .TablespaceRecord.Type type = 2;
    /**
     * <code>optional .TablespaceRecord.Type type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>optional .TablespaceRecord.Type type = 2;</code>
     */
    org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type getType();

    // optional string instanceName = 3;
    /**
     * <code>optional string instanceName = 3;</code>
     *
     * <pre>
     *if not specified then instanceName = tablespaceName
     * </pre>
     */
    boolean hasInstanceName();
    /**
     * <code>optional string instanceName = 3;</code>
     *
     * <pre>
     *if not specified then instanceName = tablespaceName
     * </pre>
     */
    java.lang.String getInstanceName();
    /**
     * <code>optional string instanceName = 3;</code>
     *
     * <pre>
     *if not specified then instanceName = tablespaceName
     * </pre>
     */
    com.google.protobuf.ByteString
        getInstanceNameBytes();

    // optional string tableName = 4;
    /**
     * <code>optional string tableName = 4;</code>
     *
     * <pre>
     *used for TABLE_PARTITION and HISTOGRAM
     * </pre>
     */
    boolean hasTableName();
    /**
     * <code>optional string tableName = 4;</code>
     *
     * <pre>
     *used for TABLE_PARTITION and HISTOGRAM
     * </pre>
     */
    java.lang.String getTableName();
    /**
     * <code>optional string tableName = 4;</code>
     *
     * <pre>
     *used for TABLE_PARTITION and HISTOGRAM
     * </pre>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();

    // optional bytes partitionValue = 5;
    /**
     * <code>optional bytes partitionValue = 5;</code>
     *
     * <pre>
     * used for TABLE_PARTITION: if partitioned by value - the value
     * </pre>
     */
    boolean hasPartitionValue();
    /**
     * <code>optional bytes partitionValue = 5;</code>
     *
     * <pre>
     * used for TABLE_PARTITION: if partitioned by value - the value
     * </pre>
     */
    com.google.protobuf.ByteString getPartitionValue();

    // optional string partitionDir = 6;
    /**
     * <code>optional string partitionDir = 6;</code>
     *
     * <pre>
     * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
     * </pre>
     */
    boolean hasPartitionDir();
    /**
     * <code>optional string partitionDir = 6;</code>
     *
     * <pre>
     * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
     * </pre>
     */
    java.lang.String getPartitionDir();
    /**
     * <code>optional string partitionDir = 6;</code>
     *
     * <pre>
     * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
     * </pre>
     */
    com.google.protobuf.ByteString
        getPartitionDirBytes();

    // optional string histogramColumnName = 7;
    /**
     * <code>optional string histogramColumnName = 7;</code>
     *
     * <pre>
     *used for HISTOGRAM
     * </pre>
     */
    boolean hasHistogramColumnName();
    /**
     * <code>optional string histogramColumnName = 7;</code>
     *
     * <pre>
     *used for HISTOGRAM
     * </pre>
     */
    java.lang.String getHistogramColumnName();
    /**
     * <code>optional string histogramColumnName = 7;</code>
     *
     * <pre>
     *used for HISTOGRAM
     * </pre>
     */
    com.google.protobuf.ByteString
        getHistogramColumnNameBytes();
  }
  /**
   * Protobuf type {@code TablespaceRecord}
   *
   * <pre>
   **
   *  This is used to encode the tablespace metadata .
   * </pre>
   */
  public static final class TablespaceRecord extends
      com.google.protobuf.GeneratedMessage
      implements TablespaceRecordOrBuilder {
    // Use TablespaceRecord.newBuilder() to construct.
    private TablespaceRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TablespaceRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TablespaceRecord defaultInstance;
    public static TablespaceRecord getDefaultInstance() {
      return defaultInstance;
    }

    public TablespaceRecord getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TablespaceRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              tbsIndex_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type value = org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              instanceName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              tableName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              partitionValue_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              partitionDir_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              histogramColumnName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.yamcs.yarch.rocksdb.protobuf.Tablespace.internal_static_TablespaceRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.yamcs.yarch.rocksdb.protobuf.Tablespace.internal_static_TablespaceRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.class, org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Builder.class);
    }

    public static com.google.protobuf.Parser<TablespaceRecord> PARSER =
        new com.google.protobuf.AbstractParser<TablespaceRecord>() {
      public TablespaceRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TablespaceRecord(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TablespaceRecord> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code TablespaceRecord.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TABLE_PARTITION = 1;</code>
       */
      TABLE_PARTITION(0, 1),
      /**
       * <code>HISTOGRAM = 2;</code>
       */
      HISTOGRAM(1, 2),
      ;

      /**
       * <code>TABLE_PARTITION = 1;</code>
       */
      public static final int TABLE_PARTITION_VALUE = 1;
      /**
       * <code>HISTOGRAM = 2;</code>
       */
      public static final int HISTOGRAM_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return TABLE_PARTITION;
          case 2: return HISTOGRAM;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TablespaceRecord.Type)
    }

    private int bitField0_;
    // optional uint32 tbsIndex = 1;
    public static final int TBSINDEX_FIELD_NUMBER = 1;
    private int tbsIndex_;
    /**
     * <code>optional uint32 tbsIndex = 1;</code>
     */
    public boolean hasTbsIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 tbsIndex = 1;</code>
     */
    public int getTbsIndex() {
      return tbsIndex_;
    }

    // optional .TablespaceRecord.Type type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type type_;
    /**
     * <code>optional .TablespaceRecord.Type type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .TablespaceRecord.Type type = 2;</code>
     */
    public org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type getType() {
      return type_;
    }

    // optional string instanceName = 3;
    public static final int INSTANCENAME_FIELD_NUMBER = 3;
    private java.lang.Object instanceName_;
    /**
     * <code>optional string instanceName = 3;</code>
     *
     * <pre>
     *if not specified then instanceName = tablespaceName
     * </pre>
     */
    public boolean hasInstanceName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string instanceName = 3;</code>
     *
     * <pre>
     *if not specified then instanceName = tablespaceName
     * </pre>
     */
    public java.lang.String getInstanceName() {
      java.lang.Object ref = instanceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          instanceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string instanceName = 3;</code>
     *
     * <pre>
     *if not specified then instanceName = tablespaceName
     * </pre>
     */
    public com.google.protobuf.ByteString
        getInstanceNameBytes() {
      java.lang.Object ref = instanceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instanceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string tableName = 4;
    public static final int TABLENAME_FIELD_NUMBER = 4;
    private java.lang.Object tableName_;
    /**
     * <code>optional string tableName = 4;</code>
     *
     * <pre>
     *used for TABLE_PARTITION and HISTOGRAM
     * </pre>
     */
    public boolean hasTableName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string tableName = 4;</code>
     *
     * <pre>
     *used for TABLE_PARTITION and HISTOGRAM
     * </pre>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tableName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tableName = 4;</code>
     *
     * <pre>
     *used for TABLE_PARTITION and HISTOGRAM
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes partitionValue = 5;
    public static final int PARTITIONVALUE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString partitionValue_;
    /**
     * <code>optional bytes partitionValue = 5;</code>
     *
     * <pre>
     * used for TABLE_PARTITION: if partitioned by value - the value
     * </pre>
     */
    public boolean hasPartitionValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes partitionValue = 5;</code>
     *
     * <pre>
     * used for TABLE_PARTITION: if partitioned by value - the value
     * </pre>
     */
    public com.google.protobuf.ByteString getPartitionValue() {
      return partitionValue_;
    }

    // optional string partitionDir = 6;
    public static final int PARTITIONDIR_FIELD_NUMBER = 6;
    private java.lang.Object partitionDir_;
    /**
     * <code>optional string partitionDir = 6;</code>
     *
     * <pre>
     * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
     * </pre>
     */
    public boolean hasPartitionDir() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string partitionDir = 6;</code>
     *
     * <pre>
     * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
     * </pre>
     */
    public java.lang.String getPartitionDir() {
      java.lang.Object ref = partitionDir_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          partitionDir_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string partitionDir = 6;</code>
     *
     * <pre>
     * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPartitionDirBytes() {
      java.lang.Object ref = partitionDir_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partitionDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string histogramColumnName = 7;
    public static final int HISTOGRAMCOLUMNNAME_FIELD_NUMBER = 7;
    private java.lang.Object histogramColumnName_;
    /**
     * <code>optional string histogramColumnName = 7;</code>
     *
     * <pre>
     *used for HISTOGRAM
     * </pre>
     */
    public boolean hasHistogramColumnName() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string histogramColumnName = 7;</code>
     *
     * <pre>
     *used for HISTOGRAM
     * </pre>
     */
    public java.lang.String getHistogramColumnName() {
      java.lang.Object ref = histogramColumnName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          histogramColumnName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string histogramColumnName = 7;</code>
     *
     * <pre>
     *used for HISTOGRAM
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHistogramColumnNameBytes() {
      java.lang.Object ref = histogramColumnName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        histogramColumnName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      tbsIndex_ = 0;
      type_ = org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type.TABLE_PARTITION;
      instanceName_ = "";
      tableName_ = "";
      partitionValue_ = com.google.protobuf.ByteString.EMPTY;
      partitionDir_ = "";
      histogramColumnName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, tbsIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getInstanceNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTableNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, partitionValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getPartitionDirBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getHistogramColumnNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, tbsIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getInstanceNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTableNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, partitionValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPartitionDirBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getHistogramColumnNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TablespaceRecord}
     *
     * <pre>
     **
     *  This is used to encode the tablespace metadata .
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.yamcs.yarch.rocksdb.protobuf.Tablespace.internal_static_TablespaceRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.yamcs.yarch.rocksdb.protobuf.Tablespace.internal_static_TablespaceRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.class, org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Builder.class);
      }

      // Construct using org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tbsIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type.TABLE_PARTITION;
        bitField0_ = (bitField0_ & ~0x00000002);
        instanceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        tableName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        partitionValue_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        partitionDir_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        histogramColumnName_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.yamcs.yarch.rocksdb.protobuf.Tablespace.internal_static_TablespaceRecord_descriptor;
      }

      public org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord getDefaultInstanceForType() {
        return org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.getDefaultInstance();
      }

      public org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord build() {
        org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord buildPartial() {
        org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord result = new org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tbsIndex_ = tbsIndex_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.instanceName_ = instanceName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.tableName_ = tableName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.partitionValue_ = partitionValue_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.partitionDir_ = partitionDir_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.histogramColumnName_ = histogramColumnName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord) {
          return mergeFrom((org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord other) {
        if (other == org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.getDefaultInstance()) return this;
        if (other.hasTbsIndex()) {
          setTbsIndex(other.getTbsIndex());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasInstanceName()) {
          bitField0_ |= 0x00000004;
          instanceName_ = other.instanceName_;
          onChanged();
        }
        if (other.hasTableName()) {
          bitField0_ |= 0x00000008;
          tableName_ = other.tableName_;
          onChanged();
        }
        if (other.hasPartitionValue()) {
          setPartitionValue(other.getPartitionValue());
        }
        if (other.hasPartitionDir()) {
          bitField0_ |= 0x00000020;
          partitionDir_ = other.partitionDir_;
          onChanged();
        }
        if (other.hasHistogramColumnName()) {
          bitField0_ |= 0x00000040;
          histogramColumnName_ = other.histogramColumnName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 tbsIndex = 1;
      private int tbsIndex_ ;
      /**
       * <code>optional uint32 tbsIndex = 1;</code>
       */
      public boolean hasTbsIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 tbsIndex = 1;</code>
       */
      public int getTbsIndex() {
        return tbsIndex_;
      }
      /**
       * <code>optional uint32 tbsIndex = 1;</code>
       */
      public Builder setTbsIndex(int value) {
        bitField0_ |= 0x00000001;
        tbsIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 tbsIndex = 1;</code>
       */
      public Builder clearTbsIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tbsIndex_ = 0;
        onChanged();
        return this;
      }

      // optional .TablespaceRecord.Type type = 2;
      private org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type type_ = org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type.TABLE_PARTITION;
      /**
       * <code>optional .TablespaceRecord.Type type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .TablespaceRecord.Type type = 2;</code>
       */
      public org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type getType() {
        return type_;
      }
      /**
       * <code>optional .TablespaceRecord.Type type = 2;</code>
       */
      public Builder setType(org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .TablespaceRecord.Type type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = org.yamcs.yarch.rocksdb.protobuf.Tablespace.TablespaceRecord.Type.TABLE_PARTITION;
        onChanged();
        return this;
      }

      // optional string instanceName = 3;
      private java.lang.Object instanceName_ = "";
      /**
       * <code>optional string instanceName = 3;</code>
       *
       * <pre>
       *if not specified then instanceName = tablespaceName
       * </pre>
       */
      public boolean hasInstanceName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string instanceName = 3;</code>
       *
       * <pre>
       *if not specified then instanceName = tablespaceName
       * </pre>
       */
      public java.lang.String getInstanceName() {
        java.lang.Object ref = instanceName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          instanceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string instanceName = 3;</code>
       *
       * <pre>
       *if not specified then instanceName = tablespaceName
       * </pre>
       */
      public com.google.protobuf.ByteString
          getInstanceNameBytes() {
        java.lang.Object ref = instanceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instanceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string instanceName = 3;</code>
       *
       * <pre>
       *if not specified then instanceName = tablespaceName
       * </pre>
       */
      public Builder setInstanceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        instanceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string instanceName = 3;</code>
       *
       * <pre>
       *if not specified then instanceName = tablespaceName
       * </pre>
       */
      public Builder clearInstanceName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        instanceName_ = getDefaultInstance().getInstanceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string instanceName = 3;</code>
       *
       * <pre>
       *if not specified then instanceName = tablespaceName
       * </pre>
       */
      public Builder setInstanceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        instanceName_ = value;
        onChanged();
        return this;
      }

      // optional string tableName = 4;
      private java.lang.Object tableName_ = "";
      /**
       * <code>optional string tableName = 4;</code>
       *
       * <pre>
       *used for TABLE_PARTITION and HISTOGRAM
       * </pre>
       */
      public boolean hasTableName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string tableName = 4;</code>
       *
       * <pre>
       *used for TABLE_PARTITION and HISTOGRAM
       * </pre>
       */
      public java.lang.String getTableName() {
        java.lang.Object ref = tableName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tableName = 4;</code>
       *
       * <pre>
       *used for TABLE_PARTITION and HISTOGRAM
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        java.lang.Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tableName = 4;</code>
       *
       * <pre>
       *used for TABLE_PARTITION and HISTOGRAM
       * </pre>
       */
      public Builder setTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tableName = 4;</code>
       *
       * <pre>
       *used for TABLE_PARTITION and HISTOGRAM
       * </pre>
       */
      public Builder clearTableName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tableName = 4;</code>
       *
       * <pre>
       *used for TABLE_PARTITION and HISTOGRAM
       * </pre>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        tableName_ = value;
        onChanged();
        return this;
      }

      // optional bytes partitionValue = 5;
      private com.google.protobuf.ByteString partitionValue_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes partitionValue = 5;</code>
       *
       * <pre>
       * used for TABLE_PARTITION: if partitioned by value - the value
       * </pre>
       */
      public boolean hasPartitionValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes partitionValue = 5;</code>
       *
       * <pre>
       * used for TABLE_PARTITION: if partitioned by value - the value
       * </pre>
       */
      public com.google.protobuf.ByteString getPartitionValue() {
        return partitionValue_;
      }
      /**
       * <code>optional bytes partitionValue = 5;</code>
       *
       * <pre>
       * used for TABLE_PARTITION: if partitioned by value - the value
       * </pre>
       */
      public Builder setPartitionValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        partitionValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes partitionValue = 5;</code>
       *
       * <pre>
       * used for TABLE_PARTITION: if partitioned by value - the value
       * </pre>
       */
      public Builder clearPartitionValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        partitionValue_ = getDefaultInstance().getPartitionValue();
        onChanged();
        return this;
      }

      // optional string partitionDir = 6;
      private java.lang.Object partitionDir_ = "";
      /**
       * <code>optional string partitionDir = 6;</code>
       *
       * <pre>
       * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
       * </pre>
       */
      public boolean hasPartitionDir() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string partitionDir = 6;</code>
       *
       * <pre>
       * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
       * </pre>
       */
      public java.lang.String getPartitionDir() {
        java.lang.Object ref = partitionDir_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          partitionDir_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string partitionDir = 6;</code>
       *
       * <pre>
       * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPartitionDirBytes() {
        java.lang.Object ref = partitionDir_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          partitionDir_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string partitionDir = 6;</code>
       *
       * <pre>
       * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
       * </pre>
       */
      public Builder setPartitionDir(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        partitionDir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string partitionDir = 6;</code>
       *
       * <pre>
       * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
       * </pre>
       */
      public Builder clearPartitionDir() {
        bitField0_ = (bitField0_ & ~0x00000020);
        partitionDir_ = getDefaultInstance().getPartitionDir();
        onChanged();
        return this;
      }
      /**
       * <code>optional string partitionDir = 6;</code>
       *
       * <pre>
       * used for TABLE_PARTITION: if partition by time - subdirectory name (usually something like 2017/11)
       * </pre>
       */
      public Builder setPartitionDirBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        partitionDir_ = value;
        onChanged();
        return this;
      }

      // optional string histogramColumnName = 7;
      private java.lang.Object histogramColumnName_ = "";
      /**
       * <code>optional string histogramColumnName = 7;</code>
       *
       * <pre>
       *used for HISTOGRAM
       * </pre>
       */
      public boolean hasHistogramColumnName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string histogramColumnName = 7;</code>
       *
       * <pre>
       *used for HISTOGRAM
       * </pre>
       */
      public java.lang.String getHistogramColumnName() {
        java.lang.Object ref = histogramColumnName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          histogramColumnName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string histogramColumnName = 7;</code>
       *
       * <pre>
       *used for HISTOGRAM
       * </pre>
       */
      public com.google.protobuf.ByteString
          getHistogramColumnNameBytes() {
        java.lang.Object ref = histogramColumnName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          histogramColumnName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string histogramColumnName = 7;</code>
       *
       * <pre>
       *used for HISTOGRAM
       * </pre>
       */
      public Builder setHistogramColumnName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        histogramColumnName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string histogramColumnName = 7;</code>
       *
       * <pre>
       *used for HISTOGRAM
       * </pre>
       */
      public Builder clearHistogramColumnName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        histogramColumnName_ = getDefaultInstance().getHistogramColumnName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string histogramColumnName = 7;</code>
       *
       * <pre>
       *used for HISTOGRAM
       * </pre>
       */
      public Builder setHistogramColumnNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        histogramColumnName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TablespaceRecord)
    }

    static {
      defaultInstance = new TablespaceRecord(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TablespaceRecord)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TablespaceRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TablespaceRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020tablespace.proto\"\352\001\n\020TablespaceRecord\022" +
      "\020\n\010tbsIndex\030\001 \001(\r\022$\n\004type\030\002 \001(\0162\026.Tables" +
      "paceRecord.Type\022\024\n\014instanceName\030\003 \001(\t\022\021\n" +
      "\ttableName\030\004 \001(\t\022\026\n\016partitionValue\030\005 \001(\014" +
      "\022\024\n\014partitionDir\030\006 \001(\t\022\033\n\023histogramColum" +
      "nName\030\007 \001(\t\"*\n\004Type\022\023\n\017TABLE_PARTITION\020\001" +
      "\022\r\n\tHISTOGRAM\020\002B\"\n org.yamcs.yarch.rocks" +
      "db.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TablespaceRecord_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TablespaceRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TablespaceRecord_descriptor,
              new java.lang.String[] { "TbsIndex", "Type", "InstanceName", "TableName", "PartitionValue", "PartitionDir", "HistogramColumnName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
